# <center><font color ="red">Cours  :   </font></center>
# <center><font color ="red">La boucle bornée for</font></center>

# <font color=#3D6BBC > Que fait ce programme? Le traduire en langage Python.</font>

![center](ex1.png)

In [1]:
for i in range(3):    
    print(i)  
print("end")


0
1
2
end


# <font color=#3D6BBC > Que fait ce programme? Le traduire en langage Python.</font>

![center](ex2.png)

In [7]:
import numpy as np

tab= [[0]*5 for i in range(3)]
#print(np.array(tab))

for y in range(3):
    for x in range(5):
        tab[y][x]=1
        
print(np.array(tab))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# <font color=#3D6BBC > Ecrire un programme pour créer un carré de 5 x 5 avec des 1</font>

![center](ex3.png)

In [8]:
import numpy as np

tab= [[0]*5 for i in range(5)]
#print(np.array(tab))

for y in range(5):
    for x in range(5):
        tab[y][x]=1
        
print(np.array(tab))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# <font color=#3D6BBC > Ecrire un programme pour créer un carré de 5 x 5 avec des 1 sur la diagonale uniquement.</font>